const tokenHelper = {
    validToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTEsImVtYWlsIjoia2FyYW5nd2FtNzkxMDBAZ21haWwuY29tIiwiZmlyc3RuYW1lIjoiRmVsaXgiLCJsYXN0bmFtZSI6IiBNdWdpc2hhIiwidXNlcm5hbWUiOiJrZTBtbTQwIiwiaWF0IjoxNTc1NjA3Mjc4fQ.ZLFGM6j9iJ62KOAaDtMu4_ozx-MOvmhNkTPnTmU2_Qs',
    invalidToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTEsImVtYWlsIjoia2FyYW5nd2FtNzkxMDBAZ21haWwuY29tIiwiZmlyc3RuYW1lIjoiRmVsaXgiLCJsYXN0bmFtZSI6IiBNdWdpc2hhIiwidXNlcm5hbWUiOiJrZTBtbTQwIiwiaWF0IjoxNTc1NjA3Mjc4fQ.ZLFGM6j9iJ62KOAaDtMu4_ozx-MOvmhNkTPnTmU2'
}

export default tokenHelper;